export const sampleDeals = [
  {
    id: 'deal-kimbap',
    source: 'merchant',
    saleType: 'group',
    category: '식사',
    store: '김밥천국 화곡점',
    title: '든든한 분식 세트',
    description: '퇴근 전 같이 주문하면 매장 방문 수령으로 할인되는 공동구매입니다.',
    address: '화곡역 5번 출구 근처',
    distance: '550m',
    deadline: '오늘 21:00',
    methods: ['픽업', '그룹배달'],
    originalPrice: 14000,
    discountRate: 10,
    current: 3,
    target: 5,
    likes: 18,
    image: 'https://images.unsplash.com/photo-1553163147-622ab57be1c7?auto=format&fit=crop&w=900&q=80',
    menu: [
      { id: 'm1', name: '김밥 세트', price: 6500, option: '기본' },
      { id: 'm2', name: '떡볶이 컵', price: 4500, option: '순한맛' },
      { id: 'm3', name: '어묵 국물', price: 2000, option: '추가' },
    ],
  },
  {
    id: 'deal-cafe',
    source: 'merchant',
    saleType: 'instant',
    category: '카페',
    store: '동네 카페 모닝',
    title: '아메리카노 10잔 번들',
    description: '한가한 시간대에 선착순으로 바로 할인받아 픽업할 수 있는 상품입니다.',
    address: '판교로 289번길',
    distance: '820m',
    deadline: '45분 남음',
    methods: ['픽업', '택배'],
    eventStart: '14:30',
    eventEnd: '16:00',
    originalPrice: 30000,
    discountRate: 20,
    current: 7,
    target: 10,
    likes: 42,
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=900&q=80',
    menu: [
      { id: 'm1', name: '아메리카노', price: 2400, option: 'ICE' },
      { id: 'm2', name: '카페라떼', price: 3900, option: 'HOT' },
      { id: 'm3', name: '콜드브루', price: 4200, option: 'ICE' },
    ],
  },
  {
    id: 'deal-dessert',
    source: 'merchant',
    saleType: 'group',
    category: '간식',
    store: '배스킨라빈스 목동점',
    title: '패밀리 아이스크림 나눔',
    description: '한 장소에서 함께 수령하는 그룹배달 테스트 상품입니다.',
    address: '목동 현대백화점 앞',
    distance: '1.2km',
    deadline: '2시간 남음',
    methods: ['그룹배달', '픽업'],
    hostMatched: true,
    originalPrice: 26000,
    discountRate: 5,
    current: 2,
    target: 4,
    likes: 9,
    image: 'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=900&q=80',
    menu: [
      { id: 'm1', name: '파인트', price: 9800, option: '3가지 맛' },
      { id: 'm2', name: '쿼터', price: 18500, option: '4가지 맛' },
      { id: 'm3', name: '패밀리', price: 24700, option: '5가지 맛' },
    ],
  },
];

export const sampleCommunityGroups = [
  {
    id: 'community-pizza',
    source: 'customer',
    saleType: 'community',
    category: '음식',
    store: '소식자 모임',
    title: '피자 한 판 반 나눠 가실 분?',
    description: '피자 한 판은 부담스러워서 동네에서 같이 나눌 분을 모집합니다.',
    address: '화곡역 5번 출구 근처',
    distance: '480m',
    deadline: '오늘 20:30',
    methods: ['픽업', '그룹배달'],
    originalPrice: 24000,
    discountRate: 0,
    current: 1,
    target: 2,
    likes: 6,
    image: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=900&q=80',
    menu: [{ id: 'cm1', name: '피자 반판 예상분', price: 12000, option: '호스트와 나눔' }],
  },
  {
    id: 'community-costco',
    source: 'customer',
    saleType: 'community',
    category: '장보기/마트',
    store: '대용량 나눔',
    title: '코스트코 체리 같이 나눠 사실 분',
    description: '대용량 상품을 필요한 만큼 나눠 사는 테스트 그룹입니다.',
    address: '판교로 289번길',
    distance: '820m',
    deadline: '내일 11:00',
    methods: ['픽업'],
    originalPrice: 36000,
    discountRate: 0,
    current: 2,
    target: 4,
    likes: 11,
    image: 'https://images.unsplash.com/photo-1528821128474-27f963b062bf?auto=format&fit=crop&w=900&q=80',
    menu: [{ id: 'cm2', name: '체리 나눔 1팩', price: 9000, option: '예상 분담금' }],
  },
  {
    id: 'community-delivery',
    source: 'customer',
    saleType: 'community',
    category: '카페',
    store: '배달비 절약',
    title: '메가커피 단체주문 같이 하실 분',
    description: '같은 건물에서 배달비를 아끼기 위해 함께 주문하는 그룹입니다.',
    address: '목동 현대백화점 앞',
    distance: '1.2km',
    deadline: '오늘 15:00',
    methods: ['배달', '픽업'],
    originalPrice: 18000,
    discountRate: 0,
    current: 3,
    target: 5,
    likes: 15,
    image: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c?auto=format&fit=crop&w=900&q=80',
    menu: [{ id: 'cm3', name: '음료 예상분', price: 4500, option: '메뉴별 정산' }],
  },
];

export const eventDefinitions = [
  { name: 'profile_submitted', label: '테스트 회원정보 입력' },
  { name: 'profile_logged_out', label: '테스트 로그아웃' },
  { name: 'screen_view', label: '화면 방문' },
  { name: 'screen_dwell', label: '화면별 체류시간' },
  { name: 'open_listing', label: '공동구매 상세 진입' },
  { name: 'like_clicked', label: '좋아요 클릭' },
  { name: 'share_clicked', label: '공유 버튼 클릭' },
  { name: 'join_started', label: '공동구매 참여 시작' },
  { name: 'quantity_changed', label: '수량 변경' },
  { name: 'method_selected', label: '수령방식 선택' },
  { name: 'instant_checkout_started', label: '선착순 즉시할인 신청 시작' },
  { name: 'checkout_started', label: '신청 완료 버튼 클릭' },
  { name: 'purchase_completed', label: '공동구매 참여 완료' },
  { name: 'group_created', label: '그룹방 생성 완료' },
  { name: 'group_image_uploaded', label: '사용자 그룹 이미지 변경' },
  { name: 'host_applied', label: '호스트 지원' },
  { name: 'survey_submitted', label: '설문 제출' },
  { name: 'owner_product_created', label: '사장님 상품 등록' },
  { name: 'source_filter_clicked', label: '게시글 유형 필터' },
  { name: 'sale_type_selected', label: '판매 방식 선택' },
  { name: 'bottom_tab_clicked', label: '하단 탭 클릭' },
  { name: 'csv_exported', label: 'CSV 데이터 추출' },
];
